### ISSUE TITLE
Не працює для міста назва якого складається з кількох слів

### ISSUE THREAD

**Issue by alex-79** [dontgiveafish/smartdelivery-plugins#4]
Не працює на прикладі Кривого Рогу (місто точно є в базі Нової Пошти)

http://api.smartdelivery.com.ua/v1/houses?city=%D0%9A%D1%80%D0%B8%D0%B2%D0%B8%D0%B9%20%D0%A0%D1%96%D0%B3&language=ua

{"status":"fail","messages":["city not found"],"data":null}

**Comment by abagayev** [comment]
Дякую за багрепорт! За добу буде вирішено.

**Comment by abagayev** [comment]
Fixed!

http://api.smartdelivery.com.ua/v1/houses?city=Кривий%20Ріг
http://api.smartdelivery.com.ua/v1/houses?city=Жовті%20Води
http://api.smartdelivery.com.ua/v1/houses?city=Івано-Франківськ
