### ISSUE TITLE
Mixed content error (https - http)

### ISSUE THREAD

**Issue by art-voloshyn** [dontgiveafish/smartdelivery-plugins#8]
My site work via https protocol and when i want get data from your api - receive the error:

Mixed Content: The page at 'https://vseprosto.ua/checkout/confirm' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.smartdelivery.com.ua/v1//houses?city=%D0%9A%D0%B8%D0%B5%D0%B2&language=ru&service_filter%5B%5D=novaposhta'. This request has been blocked; the content must be served over HTTPS.

Can you move your api to https protocol?

**Comment by abagayev** [comment]
Yes, will be done in a few days.
